services:
  # docker-compose run --rm --service-ports app
  # service-ports is for port mapping based on yaml file
  # otherwise use -p 8080:80 for custom port mapping
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: